# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fdc709f788a6deba71d5bdb235313e3b183ee56d49a8f6f82bb4c8f934815ecb986a26896993f41a9a6acf9b9a5ef28009b3f5e0d6859375cc2b6b0bcf63ee44

test:
  secret_key_base: 43a2fb4312eab9881ab7d9b7caec2939f1e75a50ec6a7610786cdc9925fc054ba7c5729aff032de3b22daaeb24565e132785fde686cc8c551cf0ad3fe32f8506

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
